package com.ubosque.fifa.jhs.persistence;
// Generated 8/05/2018 07:48:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private short matricula;
     private Login login;
     private String nombre;
     private String app;
     private String apm;
     private Short edad;
     private String sexo;
     private Date fechaRegistro;

    public Alumnos() {
    }

	
    public Alumnos(short matricula, Login login) {
        this.matricula = matricula;
        this.login = login;
    }
    public Alumnos(short matricula, Login login, String nombre, String app, String apm, Short edad, String sexo, Date fechaRegistro) {
       this.matricula = matricula;
       this.login = login;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.edad = edad;
       this.sexo = sexo;
       this.fechaRegistro = fechaRegistro;
    }
   
    public short getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(short matricula) {
        this.matricula = matricula;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public Short getEdad() {
        return this.edad;
    }
    
    public void setEdad(Short edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


