package com.ubosque.fifa.jhs.persistence;
// Generated 6/05/2018 04:13:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Arbitro generated by hbm2java
 */
public class Arbitro  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal idpersona;
     private Set partidos = new HashSet(0);

    public Arbitro() {
    }

	
    public Arbitro(BigDecimal id, BigDecimal idpersona) {
        this.id = id;
        this.idpersona = idpersona;
    }
    public Arbitro(BigDecimal id, BigDecimal idpersona, Set partidos) {
       this.id = id;
       this.idpersona = idpersona;
       this.partidos = partidos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(BigDecimal idpersona) {
        this.idpersona = idpersona;
    }
    public Set getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set partidos) {
        this.partidos = partidos;
    }




}


