package com.ubosque.fifa.jhs.persistence;
// Generated 6/05/2018 04:13:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadio generated by hbm2java
 */
public class Estadio  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private BigDecimal capacidad;
     private String ciudad;
     private Set partidos = new HashSet(0);

    public Estadio() {
    }

	
    public Estadio(BigDecimal id, String nombre, BigDecimal capacidad, String ciudad) {
        this.id = id;
        this.nombre = nombre;
        this.capacidad = capacidad;
        this.ciudad = ciudad;
    }
    public Estadio(BigDecimal id, String nombre, BigDecimal capacidad, String ciudad, Set partidos) {
       this.id = id;
       this.nombre = nombre;
       this.capacidad = capacidad;
       this.ciudad = ciudad;
       this.partidos = partidos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(BigDecimal capacidad) {
        this.capacidad = capacidad;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set partidos) {
        this.partidos = partidos;
    }




}


