package com.ubosque.fifa.jhs.persistence;
// Generated 6/05/2018 04:13:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadopartido generated by hbm2java
 */
public class Estadopartido  implements java.io.Serializable {


     private BigDecimal id;
     private String estado;
     private Set partidos = new HashSet(0);

    public Estadopartido() {
    }

	
    public Estadopartido(BigDecimal id, String estado) {
        this.id = id;
        this.estado = estado;
    }
    public Estadopartido(BigDecimal id, String estado, Set partidos) {
       this.id = id;
       this.estado = estado;
       this.partidos = partidos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set partidos) {
        this.partidos = partidos;
    }




}


