package com.ubosque.fifa.jhs.persistence;
// Generated 8/05/2018 07:48:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private BigDecimal poblacion;
     private String capital;
     private Set tipodocumentos = new HashSet(0);
     private Set partidosForEquipovisitante = new HashSet(0);
     private Set tecnicos = new HashSet(0);
     private Set partidosForEquipolocal = new HashSet(0);

    public Pais() {
    }

	
    public Pais(BigDecimal id, String nombre, BigDecimal poblacion, String capital) {
        this.id = id;
        this.nombre = nombre;
        this.poblacion = poblacion;
        this.capital = capital;
    }
    public Pais(BigDecimal id, String nombre, BigDecimal poblacion, String capital, Set tipodocumentos, Set partidosForEquipovisitante, Set tecnicos, Set partidosForEquipolocal) {
       this.id = id;
       this.nombre = nombre;
       this.poblacion = poblacion;
       this.capital = capital;
       this.tipodocumentos = tipodocumentos;
       this.partidosForEquipovisitante = partidosForEquipovisitante;
       this.tecnicos = tecnicos;
       this.partidosForEquipolocal = partidosForEquipolocal;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(BigDecimal poblacion) {
        this.poblacion = poblacion;
    }
    public String getCapital() {
        return this.capital;
    }
    
    public void setCapital(String capital) {
        this.capital = capital;
    }
    public Set getTipodocumentos() {
        return this.tipodocumentos;
    }
    
    public void setTipodocumentos(Set tipodocumentos) {
        this.tipodocumentos = tipodocumentos;
    }
    public Set getPartidosForEquipovisitante() {
        return this.partidosForEquipovisitante;
    }
    
    public void setPartidosForEquipovisitante(Set partidosForEquipovisitante) {
        this.partidosForEquipovisitante = partidosForEquipovisitante;
    }
    public Set getTecnicos() {
        return this.tecnicos;
    }
    
    public void setTecnicos(Set tecnicos) {
        this.tecnicos = tecnicos;
    }
    public Set getPartidosForEquipolocal() {
        return this.partidosForEquipolocal;
    }
    
    public void setPartidosForEquipolocal(Set partidosForEquipolocal) {
        this.partidosForEquipolocal = partidosForEquipolocal;
    }




}


