package com.ubosque.fifa.jhs.persistence;
// Generated 8/05/2018 07:48:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Partidoconvocados generated by hbm2java
 */
public class Partidoconvocados  implements java.io.Serializable {


     private BigDecimal id;
     private Jugador jugador;
     private Partido partido;
     private BigDecimal titular;

    public Partidoconvocados() {
    }

    public Partidoconvocados(BigDecimal id, Jugador jugador, Partido partido, BigDecimal titular) {
       this.id = id;
       this.jugador = jugador;
       this.partido = partido;
       this.titular = titular;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public BigDecimal getTitular() {
        return this.titular;
    }
    
    public void setTitular(BigDecimal titular) {
        this.titular = titular;
    }




}


