package com.ubosque.fifa.jhs.persistence;
// Generated 6/05/2018 04:13:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Penalizacion generated by hbm2java
 */
public class Penalizacion  implements java.io.Serializable {


     private BigDecimal idpenalizacion;
     private Jugador jugador;
     private Partido partido;
     private Reglas reglas;

    public Penalizacion() {
    }

    public Penalizacion(BigDecimal idpenalizacion, Jugador jugador, Partido partido, Reglas reglas) {
       this.idpenalizacion = idpenalizacion;
       this.jugador = jugador;
       this.partido = partido;
       this.reglas = reglas;
    }
   
    public BigDecimal getIdpenalizacion() {
        return this.idpenalizacion;
    }
    
    public void setIdpenalizacion(BigDecimal idpenalizacion) {
        this.idpenalizacion = idpenalizacion;
    }
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public Reglas getReglas() {
        return this.reglas;
    }
    
    public void setReglas(Reglas reglas) {
        this.reglas = reglas;
    }




}


