package com.ubosque.fifa.jhs.persistence;
// Generated 8/05/2018 07:48:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private BigDecimal id;
     private Tipodocumento tipodocumento;
     private String documento;
     private String nombres;
     private String apellidos;
     private Set usuarios = new HashSet(0);
     private Set jugadors = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set tecnicos = new HashSet(0);

    public Persona() {
    }

	
    public Persona(BigDecimal id, Tipodocumento tipodocumento, String documento, String nombres, String apellidos) {
        this.id = id;
        this.tipodocumento = tipodocumento;
        this.documento = documento;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Persona(BigDecimal id, Tipodocumento tipodocumento, String documento, String nombres, String apellidos, Set usuarios, Set jugadors, Set logins, Set tecnicos) {
       this.id = id;
       this.tipodocumento = tipodocumento;
       this.documento = documento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.usuarios = usuarios;
       this.jugadors = jugadors;
       this.logins = logins;
       this.tecnicos = tecnicos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set jugadors) {
        this.jugadors = jugadors;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getTecnicos() {
        return this.tecnicos;
    }
    
    public void setTecnicos(Set tecnicos) {
        this.tecnicos = tecnicos;
    }




}


