package com.ubosque.fifa.jhs.persistence;
// Generated 8/05/2018 07:48:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tecnico generated by hbm2java
 */
public class Tecnico  implements java.io.Serializable {


     private BigDecimal id;
     private Pais pais;
     private Persona persona;
     private Tipotecnico tipotecnico;

    public Tecnico() {
    }

    public Tecnico(BigDecimal id, Pais pais, Persona persona, Tipotecnico tipotecnico) {
       this.id = id;
       this.pais = pais;
       this.persona = persona;
       this.tipotecnico = tipotecnico;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Tipotecnico getTipotecnico() {
        return this.tipotecnico;
    }
    
    public void setTipotecnico(Tipotecnico tipotecnico) {
        this.tipotecnico = tipotecnico;
    }




}


