package com.ubosque.fifa.jhs.persistence;
// Generated 8/05/2018 07:48:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipodocumento generated by hbm2java
 */
public class Tipodocumento  implements java.io.Serializable {


     private BigDecimal id;
     private Pais pais;
     private String tipo;
     private String validacion;
     private Set personas = new HashSet(0);

    public Tipodocumento() {
    }

	
    public Tipodocumento(BigDecimal id, Pais pais, String tipo, String validacion) {
        this.id = id;
        this.pais = pais;
        this.tipo = tipo;
        this.validacion = validacion;
    }
    public Tipodocumento(BigDecimal id, Pais pais, String tipo, String validacion, Set personas) {
       this.id = id;
       this.pais = pais;
       this.tipo = tipo;
       this.validacion = validacion;
       this.personas = personas;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getValidacion() {
        return this.validacion;
    }
    
    public void setValidacion(String validacion) {
        this.validacion = validacion;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


